### ISSUE TITLE
docs do not provide command for creating a superuser

### ISSUE THREAD

**Issue by Talha-Rizwan** [overhangio/tutor-credentials#13]
### Problem:
The superuser of tutor lms is not authorized to login to tutor credentials admin, hence `tutor local do createuser --staff --superuser yourusername user@email.com` fails here. Readme don't provide any directions on how to create a superuser for credentials plugin.

**Solution**:
The way we can create a superuser is `tutor local run credentials ./manage.py createsuperuser`. This works perfectly fine, only need to be added to Readme.

**Comment by Faraz32123** [comment]
added the command for creating credentials superuser in readme in this [PR](https://github.com/overhangio/tutor-credentials/pull/11)

**Comment by Faraz32123** [comment]
closing this issue as it is addresses in this [PR](https://github.com/overhangio/tutor-credentials/pull/11) that is merged.
