### ISSUE TITLE
No `master` branch

### ISSUE THREAD

**Issue by CodeWithEmad** [overhangio/tutor-credentials#21]
I have noticed that this plugin does not have a `master` branch and instead uses `main` as the primary branch. While this may seem like no issue, it has caused some inconvenience when running certain scripts in a tmux env with `synchronize-panes on`. I had to manually perform extra steps for this plugin, which made managing multiple plugins more difficult. 
I would like to request the replace of the `main` with the `master` branch for this plugin.

**Comment by CodeWithEmad** [comment]
Okay, I'll take care of the link. just kindly create `master` branch from `main`.

**Comment by Faraz32123** [comment]
@CodeWithEmad, Now this tutor plugin is updated with branch named master as default branch. 
Moving this issue to Done.
