### ISSUE TITLE
Wrong default site configuration

### ISSUE THREAD

**Issue by Silidrone** [overhangio/tutor-credentials#30]
I freshly installed tutor version 17.0.0 and I suppose with the new host (local.edly.io) there is a problem in the site configuration of credentials service. I apologize if this is a problem on my end, but I highly doubt it as I freshly installed the credentials plugin and just enabled it.

When I run copy_catalog command, I get:
![Screenshot from 2024-01-17 13-04-38](https://github.com/overhangio/tutor-credentials/assets/17169590/2f4729e2-9c60-4ee1-a4e7-b0a8a35eba82)
And inside admin, the site configuration is:
![Screenshot from 2024-01-17 13-04-07](https://github.com/overhangio/tutor-credentials/assets/17169590/2536d080-2703-4a17-b5af-a13bb02d470f)
Needless to say, when I change `http` to `http://`, everything works.

tutor-credentials plugin is version 17.0.0

**Comment by DawoudSheraz** [comment]
This appears to be an error in tutor-credentials init task (https://github.com/overhangio/tutor-credentials/blob/master/tutorcredentials/templates/credentials/tasks/credentials/init#L11). Comparing it with tutor-discovery (https://github.com/overhangio/tutor-discovery/blob/master/tutordiscovery/templates/discovery/tasks/discovery/init#L22), the `://` are present in discovery.
