### ISSUE TITLE
tutor-credentials codebase Python 3.12 upgrade

### ISSUE THREAD

**Issue by DawoudSheraz** [overhangio/tutor-credentials#34]
- [x] Ensure tutor-credentials is compatible with Python 3.12
- [ ] Update Python to 3.12 in Dockerfile for nightly and ensure the image builds as expected. The changes would be merged to nightly. This task would rely on upgrade of credentials to Python 3.12

See https://github.com/overhangio/tutor/issues/1004 for the context.

**Comment by regisb** [comment]
Is there an upstream issue to track the 3.12 upgrade in openedx/credentials? You should report your findings to the repo maintainers.

**Comment by DawoudSheraz** [comment]
https://github.com/openedx/public-engineering/issues/234 does not specify any issue on credentials, I dont see any active issue on https://github.com/openedx/credentials/ either. Though there is a PR up to add Python 3.11 and 3.12 support https://github.com/openedx/credentials/pull/2389

**Comment by DawoudSheraz** [comment]
The upstream PR has been merged, this should be unblocked now.

**Comment by GlugovGrGlib** [comment]
As CC to credentials repo I'll take the problem with didkit to work.
I'll update this issue as soon as it resolved

**Comment by justinhynes** [comment]
This seems to also be an issue for Credentials with Python 3.11 too -- I opened an issue yesterday against the Credentials repo to share my findings thus far: https://github.com/openedx/credentials/issues/2477.

**Comment by Faraz32123** [comment]
closing this issue as its [PR](https://github.com/overhangio/tutor-credentials/pull/41) is merged.
NOTES:
- [Credentials](https://github.com/openedx/credentials/) codebase is not compatible with python3.12 yet.
- CI: temporarily skipping building on arm64. As the upstream credentials repo seems to be breaking on arm64 and they are skipping arm64 builds as well due to the didkit package dependency not available on arm64 yet.

**Comment by GlugovGrGlib** [comment]
Hey all didkit issue was resolved in version [v0.3.3](https://github.com/spruceid/didkit-python/releases/tag/v0.3.3), after merging requirements upgrade PR into credentials, the compatibility with python 3.12 and arm64 will be fully resolved.
